name: terraform

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.6

  validate:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run a terraform validate command
        working-directory: ./terraform
        run: |
          terraform init -backend=false
          terraform validate
  fmt:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run a terraform fmt command
        working-directory: ./terraform
        run: terraform fmt -check -recursive
