name: terraform validate

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2.0.3
        with:
          terraform_version: 1.3.6
      - name: Run a terraform plan command
        working-directory: ./terraform
        run: |
          terraform init -backend=false
          terraform validate
